# Generated by Django 5.1.2 on 2025-06-08 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_clientsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 6, 8, 17, 31, 57, 476365, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
