# Generated by Django 5.1.2 on 2025-06-08 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_clientsubscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 6, 8, 20, 45, 34, 10072, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
