# Generated by Django 5.1.2 on 2025-06-09 07:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_clientsubscription_expires_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="user",
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "owner"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="accounts.clientsubscription",
            ),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="business_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="expires_at",
            field=models.DateTimeField(
                default=1,
                verbose_name=datetime.datetime(
                    2026, 6, 9, 7, 36, 53, 12324, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("cashier", "Cashier"),
                ],
                max_length=10,
            ),
        ),
    ]
