# Generated by Django 5.1.2 on 2025-06-09 13:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_clientsubscription_expires_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientsubscription",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="stripe_subscription_id",
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="business_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="expires_at",
            field=models.DateTimeField(
                default=1,
                verbose_name=datetime.datetime(
                    2026, 6, 9, 13, 36, 43, 444163, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default="",
                max_length=20,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
    ]
