# Generated by Django 5.1.2 on 2025-06-09 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_clientsubscription_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expires_at",
            field=models.DateTimeField(
                default=1,
                verbose_name=datetime.datetime(
                    2026, 6, 9, 14, 45, 37, 119633, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
