# Generated by Django 5.1.2 on 2025-06-10 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_clientsubscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expires_at",
            field=models.DateTimeField(
                default=1,
                verbose_name=datetime.datetime(
                    2026, 6, 10, 7, 24, 52, 317919, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
