# Generated by Django 5.1.2 on 2025-06-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_clientsubscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
