# Generated by Django 5.1.2 on 2025-06-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_clientsubscription_expires_at"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="salesreport",
            name="reports_sal_report__92f498_idx",
        ),
        migrations.RemoveIndex(
            model_name="salesreport",
            name="reports_sal_start_d_de74dd_idx",
        ),
        migrations.AddField(
            model_name="salesreport",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_reports",
                to="accounts.clientsubscription",
            ),
        ),
        migrations.AddIndex(
            model_name="salesreport",
            index=models.Index(
                fields=["subscription", "report_date"],
                name="reports_sal_subscri_a642b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesreport",
            index=models.Index(
                fields=["subscription", "start_date", "end_date"],
                name="reports_sal_subscri_3eefda_idx",
            ),
        ),
    ]
